# Generated by Django 5.0.3 on 2024-04-07 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='goal',
            new_name='feedback_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='description',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='title',
        ),
        migrations.AddField(
            model_name='feedback',
            name='bad_feedback',
            field=models.TextField(default='', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='good_feedback',
            field=models.TextField(default='', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_archived',
            field=models.BooleanField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_deleted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='other_feedback',
            field=models.TextField(default='', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='review_comment',
            field=models.TextField(default='', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='team_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='team_member_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member_name', models.CharField(max_length=200)),
                ('team_id', models.IntegerField()),
                ('team_member_id', models.IntegerField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='feedback.feedback')),
            ],
        ),
    ]
