# Generated by Django 5.0.3 on 2024-04-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_goal_feedback_feedback_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='bad_feedback',
            field=models.TextField(default=None, max_length=800),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='good_feedback',
            field=models.TextField(default=None, max_length=800),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='other_feedback',
            field=models.TextField(default=None, max_length=800),
        ),
    ]
